#!/bin/sh
# Copyright (c) 2019 Aidan Williams
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ -f ~/.cache/last_power ]; then
  last_power=$(cat ~/.cache/last_power)
else
  last_power=0
fi

if [ $DP_PERCENTAGE -le 10 ] && [ $last_power -gt 10 ]; then
  notify-send \
    "Battery Critical" \
    "Your laptop is running on very low power, and will die soon, if not plugged in" \
    -i "$DP_ICONNAME" \
    -u critical
elif [ $DP_PERCENTAGE -le 20 ] && [ $last_power -gt 20 ]; then
  notify-send \
    "Battery Low" \
    "Your laptop is running on low power, please plug it in soon" \
    -i "$DP_ICONNAME" \
    -u normal
fi

echo $DP_PERCENTAGE > ~/.cache/last_power
